[package]
name = "diff-match-patch-rs-bench"
version = "0.1.0"
edition = "2021"
authors = ["Anubhab Bandyopadhyay"]

[dependencies]
criterion = "0"
diff-match-patch-rs = { git = "https://github.com/AnubhabB/diff-match-patch-rs.git", branch = "main", default-features = false } # this crate
diff_match_patch = "0.1.1"
diffmatchpatch = "0.0.4"
dmp = "0.2.0"
dissimilar = "1.0.9"


[[bench]]
name = "diff"
harness = false